apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wireguard.fullname" . }}-secret
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.wireguard.password | b64enc }}
