apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.nfsClient.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    argocd.argoproj.io/sync-options: Replace=true
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ .Values.nfs.server }}
  share: {{ .Values.storageClasses.nfsClient.share }}
reclaimPolicy: {{ .Values.storageClasses.nfsClient.reclaimPolicy }}
volumeBindingMode: Immediate
allowVolumeExpansion: true
