{{- range .Values.namespaces.infrastructure }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
    pod-security.kubernetes.io/enforce: {{ .enforce }}
    pod-security.kubernetes.io/audit: {{ .audit }}
    pod-security.kubernetes.io/warn: {{ .warn }}
    {{- with $.Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

{{- range .Values.namespaces.applications }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
    pod-security.kubernetes.io/enforce: {{ .enforce }}
    pod-security.kubernetes.io/audit: {{ .audit }}
    pod-security.kubernetes.io/warn: {{ .warn }}
    {{- with $.Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}