apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp-secret
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: grafana-smtp-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
  encryptedData:
    GF_SMTP_PASSWORD: "AgBPG9wXsHG86UUv6CMXSexIeoApNtkLoF4LyiG/2IGT92cLQv0gJpt1yearqinLyXjUwWKLJDhqc/DNOrd8j0zR5xMpdfDm/HIDuorWTazh3QogwU/B1CVjmtggNkMTLQw77LPuu0Nb45C4HWjCGZGeITaj/wJlhgVeOfxbPTAVX8SeH1ISm4RPLTwwAKBiof+N+1411UfiItl7rfBOJiMEQ6WxTZbpL+SI98D4jSqtOe2gG597GW+AU12uvYsS22cNAyxUoObMZYPbU4u4+EcWJb/nJYxn4ijifBxzSfpm4XOtIWd3YHOFXTa41xVvGaQ1LHqm7KRHv/gIJxVTYhSONvF3q6gKlFPqRyJoH+xDxauzP6vF4BUqxFROzZ59POWb0xWJtNEujBD+ntq9ZfXr9en+czmfyaGDo1OtW52NG0k8TTPsXoLRZkYeIxejvti4WPFOY0Yr+2TRrvDNUs1mhvYWkFfbN0wak8L+acEUauS02r4dpG8fFSAsB0SBF2rFkGrQ40bz0dOwMWyuuxmmuAW3hD40+OIhyvytPc+RCvWWWvBoaiiQVh64evo1womtNaUuJY/hDA/lIL5ESjC6MgoOytgek2A21lP6KPe42wBDaRVw5ja6V3ggw8K73Y7JDLDPSihWMokkHxlHn1lSh817zBP5VLo2cQoyNSY/640/nURb9xkh1iL8YqQ4jqkjlAf8rrCew8FBtJKgOCgy7Yf"
    GF_SMTP_USER: "AgCMZgnh0VEi+ZrOssEdQXwI9c/4J/NMYEQprHQuWSU5U0Amu/gL9Acq6ZIIBpNsNbESBLUTFALTFtzeO8zqS5pBchOmUNzKrVHR5FCxQYAh0LgTqd6Gi7dxJvuOq1DG9s@"
