apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-smtp-secret
  namespace: {{ .Release.Namespace | default "monitoring-production" }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: grafana-smtp-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/grafana/smtp
        property: username
    - secretKey: password
      remoteRef:
        key: secret/grafana/smtp
        property: password