{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-smtp-secret",
    "namespace": "monitoring-production"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-smtp-secret",
        "namespace": "monitoring-production"
      }
    },
    "encryptedData": {
      "GF_SMTP_PASSWORD": "AgCW6i51PPn68IRFAvwFEqctbLCIWsc5SGoI3MZATO6ze+cUQ9mAdIi8ukH4/3bRNJqDfTcWyyKgzCtWQJZeHoTCtNIeqJy/eREqXth8HMI/3GfWE8Ki1hXi85La2vIQNJs4I23vxjUTgNS/x5B/UYYjdNb+nSBmYoxGwOsSrm4rutKvrrN1Pzd3uLhdPw8HIJM0ySlyhlgzg7Pxj50L5N7MJY8tgfMUHzp+FJnR1jj2kpOI0k+oM+npoUy3d3Uru19smxiPu84a+6HxjcCLL9VIGNELsZ2ksz9oGCQkP6fuihJ0KuGQLy7ZfXB4Bi8I3U5Kr50ek+O4UE5/TWdqFmWaAFdAgZN4LBMp+toLGEfazL2tV83bfJwsSCNC0A/JpGhEK7bkxtiDnDbDvzlzApr98xtMKOk32NaW9Ahm9OD6Q6DceoqiY0+vSV/roSVxEYgqbXFFj14Tbh2t4v1Xe0jJMezOHZ5MpKmOe6A0QRbcvqV/ZmJTxh/K0sK2bMci4Bmf1nb0cSJTshX++344Ya+sGbYrTGsbiteRpe1+Lb0g1NuG0shHzKWtR/Mf+jdUTwBbn0jt5GbOwSkvV1ufsLXg1D4CvfEST+K8b5qAuKtlhCSeT7dJemZ9gQFVgelcYdTADhJiqP+tlTXNu4HA40nVKbu/npVDepOn8f8+r72EQPwjOoQYDPO85Xd9vMsLrY8O/goJ/QHl95M49HlKpDn+gCA=",
      "GF_SMTP_USER": "AgAMTenHOgrm5D+iRqxwq+08x9Lm7H9Eaw7Ug9vObCuhe+FQusQ6FjxgRwPSDFLp/Akb4GYqCLB/LP3eB43/3Q14KKLQxOZyWTnGuE1ixWr56h7KZaHA0XlJR4QpMaocLyh3ayLlU1rZmqgJjjuPMShfnBTHKlAJNFpLA2gn2zy/eyNYjxtf8qcExn/EulpokpT+L8Rud0LWvhH2ckRn+uywAOyTARtHZ4kapxjjW8FAmtEQr/UyLhjjGk99E2RK7jQZFw/vh8X47mLY1VAVxueUE3+kjaDyjzyHPs3SFXYFtCwXX4xws86Dm5dfoN0J7YK439s4efltpQzalXU0L9/8hWBIwC5glbayHe2umqFwUxrH4FMstZqtkSmB4LfdjPQod7tHuQhaNF+OMXquXvJWKYOeNMxsZ/YyYNsu+ztLtuTUTsuxQSvL8s6AIrnACgDJ+I6vD8cpWvbhs5W4ckd5MiFQNWTDnwtvthij43sxEbFI2ENM7IjR4qHXBB7O7/n6W+0+BCdwjFcojtqoDchMhvlHJTsPWmk7i2OWXMHtxxPslw57VS80aQYkJZF3SfSIfQX7Ry96MixBjnHcZFWjE7eV16WDUdLEr4vXKVUW62TtgUm3olwKyJepjhjq9SFxTVLj981dgGTFMtGHOhzhTrepXDKn/0hh9m3SHzj32bHzgEZhdmxoaFKs8wKJpLGnZgUz8Zy0eesaJDxm3vzNjQ=="
    }
  }
}
