---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring-production
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgAjNRrxvTiqGVSpu6mXa8NyJEKLGxgEQlkAeUvCOrxdFLcIeO2N3AXkVgFMQiH5Wj8VJrUn/e6JebDzqQ/XD8pRkSG0rXAL4c+qwd/42XG3NSiXfOiENRndZAShTHPB9kJ3rhZUpWcBqeOJ+fdLFxh7BBrx1ZPcmevpzTbBBv9fC3286LEVNujlaxap4c5R86khnzlMs55PitFV6mSbpb6H9H1rxFxaY1Fc0Gv9fcUNlWttUNYXSjk7x9pr5kruglSWp2CnTfajFWWeXgaMchsOT5+h41ughBfMyxVhmLFTlcuHkNUt4VgNt8tbRDU0ePSJlseqr7migo3MWI00wWVNMNWRsXFQAmAqJZ/8q1TMs4yZ/TAoTKzv2sOjAn6MzXJiNfBxnh/SFenE0uux00ywWJhtH/odkg1T92Mym1BUXQkRbTICc8zW+L69KinUNcODh8p5p8y5oIsd97Ba56c7QWxz6R27AcqcO6flaFfOn+x4pUxzkdwHyN1/cBthoTuI62O5c4dAKakAFTS5OywUUy8dWMCoQ8Lx9GgV49fLhH9skSwicKsgePSOiw2LrBfx94Cm8cwn/1JhXVAG8dwFHsiir+7+N15WP4Kce5ZdYqBy4EckN500RgitVQG4xeY/PX83Wt+lGd3/KSuw90QvRYhbMnze9jS7jrvapCBIyUEj2uxntCvON/42OlXRGWSL1SVAUwblIekSoMlr8hfO
    GF_SMTP_USER: AgA1WDi8gb7OuqToRd01clW8UloVcp1uy9CjoPw8n0zKng8Um2qEfuvkhujr523KClqUeG/G/nhhg3FNL+onnF5CkZAyfO0z6CvLfTquFt+kQj76IHlN9u/Pbv5PZddbQpHVetCtD4905RX4IspZEPq97mjsWImX3ciyMEnjyJzcsDzYioO99cd3N9bczPfo+/va0zKtrtOGv1YoEfkxY9Q7BYdZzksl3vkrCR7Xy8kh/8HybnfvBPqa3OYnQnfEH0PAWzBDLLgRHX5Q5/UxImi3S3hGru1cvtF8BbpLAlSQ21Zifgmki0J5+RMN+4sCmyXCdVYIDoNISZDUDPWnhTZfwcwYFxdVLUBlR8S4D2e120nZHXS5qyjnnB/wQg6OwSBoGzWwA/w1FIXxRspNXe/HPbJXXgDlLn05pAP5yCznmNfOSTg0KxUGIGn61NiDS5amrCp++2dD14Dd9THmTlGsW/9fWlS8TwSsMYSYnrdPnSHvJ+Hw1JPM/uaSKHc9VLB9IH2VHLXI5s2haBxbz6MCnFHBwwLNAiTFQctjElx9UPM0vlhH1gNVDdI7OLcJokbqu3goKLUA9RZBsnmm/GE326qU1nDA4AlTBTd8jOx2r55EBfo59MHvoX2gwylCZB7LZ9VwAbkKxXglN79HCiPL7yiECUALfEbG3q+LI3Gd5z0EwdbDNBAdi6KtyoUnA+nV/lufEViUDM0Qk+jrZR3GzQ==
  template:
    metadata:
      name: grafana-smtp-secret
      namespace: monitoring-production
