-----BEGIN CERTIFICATE-----
MIIEzDCCArSgAwIBAgIQRwecRo8YUep5mNd7xDXdkjANBgkqhkiG9w0BAQsFADAA
MB4XDTI1MDkxMzAyNTY1MFoXDTM1MDkxMTAyNTY1MFowADCCAiIwDQYJKoZIhvcN
AQEBBQADggIPADCCAgoCggIBAKF2IckRHf/8QWZa8x4an71XuiC5XufCey9g0qi0
3dIY1ulalhy/RC6eDRVkW2DPeI9dSoFG9879/uc6Bp5tK1sNXkMG0R847+lkMKUs
tlJtCxpzxaRPvKA4ZBXNxoJisMn3TnWLbLk7fXfYSzDSrHSuakpe0L5Wryurq3hw
JBaqqoV8tj3tDctUdlpyOISF7U5knAmyxvpaqu1FKA2jOpFIpeK7y5fTW1qKE9zz
TtvJxXO8fJfJqzC2e2fxMCh4Wxk+IyBmEn8OPaFRABbJ3cEC9pu+L66bbtlR7YIz
7fp+Yeu/Jk7YxJCkWTaFG0hvDHHR6xycIms4FTEJAzQYlPP7Gzyt/2KESOHdW46P
482/dOj8MqzrDfHmGRFFWYWpa2VT0hH8PeTvHOG14q3RRFLrUFdG3NKe8taimZB6
VUT3R0f3nrxTqtuFFdAl4+dycR9+KWE0IGC+eNh8aRTnc+YVJWnp9vyAmIs8VggO
k8+ajLWyJmT3iJC7xFku7X737Yerscxtu7Zfsi1nxGWtuC4/Qb8VMPskALAfJFPj
P2rkUS4gMMUEkFA3Q8DXSZVCVRLj3rNpsJmQtesm2ejDXQxEOv+b0DLBvKRYFm/b
HZINAvclFUEe093xG5bC6VKmFq1MxoE6cTLJkq7PIC/WlUJoGrbZEHExDNpOqfEt
UiI1AgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIAATAPBgNVHRMBAf8EBTADAQH/MB0G
A1UdDgQWBBR1LgHlZ4JAyFCQR97anS5yGmMgWTANBgkqhkiG9w0BAQsFAAOCAgEA
CiYAw5ZY8qR96G9E5R+mnm4yAJ3OSn2ukqw6swmTe+a7r0J5cOs341i7w+tmstfT
Q7bnOG+bT7qss7MyHguo9RdZEt804gSsck7onWAXIbqlw1EYb3R2yp5bUiqToPvh
hjXf8x8D7FfGYNdSZDcS2Y8Ue5u0SegD36utmgxj15xZ2XXI/UhSBwSt/nB8iko/
KcZVrplOynIGTPl1QibAAwAyXYbfZQEq3ptbv/PhNRiEUg1X4CwB9JTghU1natvN
f2o6GjArlT7ebkKRkZDjLyFIqKLVF9Pe5pc2LcQgmdsBYQFoCa+ATh78dV6tIrai
mO7kpk8HnykdIBGJwW1nAcLFtqn4ZYIBjXxufqjSMs3tit0QE7Q9WKd7x1nPL2ao
kua8HtFqVNnzq42MLwEno5/N1jTWjIGULFP10e4BGEqrYkJ17FWnsC6SManes1ii
XZFVHUFUbGA3eafQHWHvObECtjKV3VhVkz1UJU/g9xg+slHDeGTxiUAMOiO3/1KV
x+a1AtVm14wKVhH0zMbya7CSAfd82+OCdPYEkmj8T4He37d6jM7Fx3qKtJD8XZJb
mBonoD7yEnBz+/Cm+wbRhkoCNXJQnqvAC5B7IwhQa3NGFZBq/HmpgilJ3ETAcBK8
B3lS4NFSXyzuKNg0/UVsBmZZDxs+4ven18nlmS7ODrs=
-----END CERTIFICATE-----
