{{- if .Values.grafanaSmtp.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp-secret
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: grafana-smtp-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
  encryptedData:
    GF_SMTP_PASSWORD: "AgBPG9wXsHG86UUv6CMXSexIeoApNtkLoF4LyiG/2IGT92cLQv0gJpt1yearqinLyXjUwWKLJDhqc/DNOrd8j0zR5xMpdfDm/HIDuorWTazh3QogwU/B1CVjmtggNkMTLQw77LPuu0Nb45C4HWjCGZGeITaj/wJlhgVeOfxbPTAVX8SeH1ISm4RPLTwwAKBiof+N+1411UfiItl7rfBOJiMEQ6WxTZbpL+SI98D4jSqtOe2gG597GW+AU12uvYsS22cNAyxUoObMZYPbU4u4+EcWJb/nJYxn4ijifBxzSfpm4XOtIWd3YHOFXTa41xVvGaQ1LHqm7KRHv/gIJxVTYhSONvF3q6gKlFPqRyJoH+xDxauzP6vF4BUqxFROzZ59POWb0xWJtNEujBD+ntq9ZfXr9en+czmfyaGDo1OtW52NG0k8TTPsXoLRZkYeIxejvti4WPFOY0Yr+2TRrvDNUs1mhvYWkFfbN0wak8L+acEUauS02r4dpG8fFSAsB0SBF2rFkGrQ40bz8O5OwMWyuuxmmuAW3hD40+OIhyvytPc+RCvWWWvBoaiiQVh64evo1womtNaUuJY/hDA/lIL5ESjC6MgoOytgek2A21lP6KPe42wBDaRVw5ja6V3ggw8K73Y7JDLDPSihWMokkHxlHn1lSh817zBP5VLo2cQoyNSY/640/nURb9xkh1iL8YqQ4jqkjlAf8rrCew8FBtJKgOCgy7Yf"
    GF_SMTP_USER: "AgCMZgnh0VEi+ZrOssEdQXwI9c/4J/NMYEQprHQuWSU5U0Amu/gL9Acq6ZIIBpNsNbESBLUTFALTFtzeO8zqS5pBchOmUNzKrVHR5FCxQYAh0LgTqd6Gi7dxJvuOq1DG9ZSwBi9J95o1a28dI353hWBPHvBgJ1EHPiIaSkukBe33gRAi3lBNnJ57E2pBlnWkO3ILyIefw2A2UoYePxDezKm/nOAkE9M08T+3OEi8XI6lOXVgnNsATZBOrTjvcFOMR95+954HgtMijDDI0A0vuppSez32zsRhMO3JNVHYR97HspfprBbEhtdiGvVWBMAzps9TJqxFpr3IX/AKgM3N42PvaJJGQm34sEha32xK2UcH8az7/WUXSXu5E6JHn/E11gF8vmxYvhHlPajBpU+B/LR4KVkJfDBmY+hbbzn2Zdb5KbJnkMCMRtLjMSdlcp6rJH5uG1s+Vl3iR/DRZjh1a2ICR/Q5lRm04oARxAjuaHjL8UjPFgQHAyV8j/Z7qWrGtuAlDOBYaV4r8aDQJQQHQ0HHqfF0Vl60rpk2947UCwEN6Lx8MdURav2Gw8drxvDjNJ/3f8OBIOzlXQMAh6Zx4mry542OsG4liE3bz+x8vOMAD7moFLWFJOr14AQCmp91/XDoGO2Pn2GuS9gprZ+EdgPEulUyNoq4TxPnSnXByXgGe99g4sCAXPLsh7YmN+IS/owXusoW2RaZs3Uc/8BMGQ1mtA=="
{{- end }}
