apiVersion: v2
name: descheduler
description: Kubernetes descheduler for automatic pod rebalancing
type: application
version: 0.1.0
appVersion: "v0.29.0"
keywords:
  - descheduler
  - scheduling
  - rebalancing
  - homelab
home: https://github.com/kubernetes-sigs/descheduler
sources:
  - https://github.com/kubernetes-sigs/descheduler
maintainers:
  - name: Lab1830
    email: admin@lab1830.com
dependencies:
  - name: descheduler
    version: "0.29.0"
    repository: https://kubernetes-sigs.github.io/descheduler/