{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "restic.serviceAccountName" . }}
  labels:
    {{- include "restic.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
