{{- if not (contains "staging" .Release.Namespace) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-access
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: 31000
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
{{- end }}
