apiVersion: v2
name: kyverno
description: Kyverno policy engine with custom policies
type: application
version: 0.1.0
dependencies:
  - name: kyverno
    version: "3.3.4"
    repository: https://kyverno.github.io/kyverno/
  - name: policy-reporter
    version: "2.24.2"
    repository: https://kyverno.github.io/policy-reporter/
