apiVersion: v2
name: vault
description: HashiCorp Vault for secrets management
type: application
version: 0.1.0
appVersion: "1.15.2"
dependencies:
  - name: vault
    version: "0.25.0"
    repository: "https://helm.releases.hashicorp.com"
keywords:
  - vault
  - secrets
  - security
home: https://www.vaultproject.io
sources:
  - https://github.com/hashicorp/vault-helm
maintainers:
  - name: Lab1830
    email: admin@lab1830.com
